# /etc/dovecot/conf.d/10-mail.conf
mail_location = maildir:~/Maildir

# Para el contenedor, almacenar correo en /var/mail
# namespace inbox {
#    inbox = yes
# }

# Ajustado para ser simple; el responsable completa la configuración real.
mail_privileged_group = mail